name: Run Drizzle Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Gerar Migração (Caso os arquivos não estejam no repositório)
        run: npm run db:generate

      - name: Listar Arquivos da Pasta Drizzle (Debug)
        run: ls -R drizzle
        if: success() # Ensures this step runs only if the previous step was successful

      - name: Rodar Migração
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run db:migrate
        if: success() # Ensures this step runs only if the previous step was successful
